# --- Defaults ---

# --- pymarl options ---
runner: "episode" # Runs 1 env for an episode
mac: "basic_mac" # Basic controller
env: "sc2" # Environment name
env_args: {} # Arguments for the environment
batch_size_run: 1 # Number of environments to run in parallel
test_nepisode: 20 # Number of episodes to test for
test_interval: 2000 # Test after {} time-steps have passed
test_greedy: True # Use greedy evaluation (if False, will set epsilon floor to 0
log_interval: 2000 # Log summary of stats after every {} time-steps
runner_log_interval: 2000 # Log runner stats (not test stats) every {} time-steps
learner_log_interval: 2000 # Log training stats every {} time-steps
t_max: 10000 # Stop running after this many time-steps
use_cuda: True # Use gpu by default unless it isn't available
buffer_cpu_only: True # If true we won't keep all of the replay buffer in vram

# --- Logging options ---
use_tensorboard: True # Log results to tensorboard
save_model: True # Save the models to disk
save_model_interval: 50000 # Save models after this many time-steps
checkpoint_path: "" # Load a checkpoint from this path,./results/models/hicluster_seed284535109_27m_vs_30m_2024-07-16_10-05-27,./results/models/MPE/mpe-SimpleAdversary-v0/qmix__829188701__2025-05-07_10-59-06
evaluate: False # Evaluate model for test_n episode episodes and quit (no training)
render: True # Render the environment when evaluating (only when evaluate == True)
load_step:  # Load model trained on this many time-steps (0 if choose max possible), 2001023, 2050025
save_replay: True # Saving the replay of the model loaded from checkpoint_path
local_results_path: "results" # Path for local results

# --- RL hyperparameters ---
gamma: 0.99
batch_size: 8 # Number of episodes to train on, before 32
buffer_size: 32 # Size of the replay buffer
lr: 0.0005 # Learning rate for agents
optim_alpha: 0.99 # RMSProp alpha
optim_eps: 0.00001 # RMSProp epsilon
grad_norm_clip: 10 # Reduce magnitude of gradients above this L2 norm
add_value_last_step: True

# --- Agent parameters ---
agent: "rnn" # Default rnn agent
hidden_dim: 64 # Size of hidden state for default rnn agent
obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: True # Include the agent's last action (one_hot) in the observation

# --- Experiment running params ---
repeat_id: 1
label: "default_label"
hypergroup: null
differ_reward: False

epsilon_anneal_time: 70000
cluster_method: "hdbscan" # kmeans, hdbscan, dpgmm